package it.gov.pagopa.cgn.portal.email;

public enum EmailNotificationEventEnum {
    NEW_AGREEMENT_REQUEST,
    DISCOUNT_TEST_REQUEST,
    AGREEMENT_REQUEST_APPROVED,
    AGREEMENT_REQUEST_REJECTED,
    HELP_REQUEST,
    DISCOUNT_SUSPENDED,
    DISCOUNT_TEST_PASSED,
    DISCOUNT_TEST_FAILED,
    DISCOUNT_EXPIRING,
    JOB_ADMIN_EYCA,
    ADMIN_EYCA
}
