version: '2'

services:
  app:
    image: 'cgn-onboarding-portal-backend:latest'
    build:
      context: .
    container_name: app
    ports:
    - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres

  db:
    image: 'postgres:11-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
