version: '2'

services:
  app:
    image: 'cgn-onboarding-portal-backend:latest'
    cpus: 1.0
    mem_limit: "1g"
    build:
      context: .
    container_name: app
    ports:
    - 9090:9090
    depends_on:
      - db
      - azurite
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication

  db:
    image: 'postgres:11-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:3.11.0'
    container_name: azurite
    ports:
      - 10000:10000
      - 10001:10001

  hub-spid-login-ms:
    container_name: hub-spid-login-ms
    build:
      context: ./auth-spid
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    command: ["yarn", "start"]
    depends_on:
      - redis
    expose:
      - "8080"
    ports:
      - "8080:8080"
      - "5859:5859"
    volumes:
      - "./certs:/usr/src/app/certs:ro"
      - "./auth-spid-config-testenv/.env:/usr/src/app/.env:ro"
  spid-testenv2:
    container_name: spid-testenv2
    image: italia/spid-testenv2:1.1.0
    ports:
      - "8088:8088"
    volumes:
      - "./auth-spid-config-testenv:/app/conf:cached"

  redis:
    container_name: redis
    image: wodby/redis:3.2-2.1.5
    ports:
      - "6379:6379"
    environment:
      REDIS_TIMEOUT: 300
      REDIS_TCP_KEEPALIVE: 60
      REDIS_MAXMEMORY: 182m
