version: '2'

services:
  app:
    image: 'cgn-onboarding-portal-backend:latest'
    cpus: 1.0
    mem_limit: "1g"
    build:
      context: .
    container_name: app
    ports:
    - 9090:9090
    depends_on:
      - db
      - azurite
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=5MB
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - CGN_PE_STORAGE_AZURE_BLOB_ENDPOINT=http://azurite:10000/devstoreaccount1
      - JAVA_OPTS=-XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+UseStringDeduplication

  db:
    image: 'postgres:11-alpine'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

  azurite:
    image: 'mcr.microsoft.com/azure-storage/azurite:3.11.0'
    container_name: azurite
    ports:
      - 10000:10000
      - 10001:10001
