
CREATE TABLE AGREEMENT_USER (
    AGREEMENT_USER_K                    VARCHAR (16),
    AGREEMENT_ID                        VARCHAR(36) NOT NULL,
    INSERT_TIME                         TIME DEFAULT NOW() NOT NULL,
    UPDATE_TIME                         TIME,
    CONSTRAINT AGREEMENT_USER_PK PRIMARY KEY (AGREEMENT_USER_K)
);
CREATE UNIQUE INDEX IDX_AGREEMENT_USER_SUBSC_ID ON AGREEMENT_USER(AGREEMENT_ID);

CREATE TABLE AGREEMENT (
    AGREEMENT_K                         VARCHAR(36) NOT NULL,
    STATE                               VARCHAR(50) NOT NULL,
    START_DATE                          DATE,
    END_DATE                            DATE,
    PROFILE_MODIFIED_DATE               DATE,
    DISCOUNTS_MODIFIED_DATE             DATE,
    DOCUMENTS_MODIFIED_DATE             DATE,
    INSERT_TIME                         TIME DEFAULT NOW() NOT NULL,
    UPDATE_TIME                         TIME,
    CONSTRAINT AGREEMENT_PK PRIMARY KEY (AGREEMENT_K),
    CONSTRAINT AGREEMENT_FK FOREIGN KEY (AGREEMENT_K) REFERENCES AGREEMENT_USER(AGREEMENT_ID)
);

CREATE TABLE REFERENT (
    REFERENT_K                          BIGINT NOT NULL,
    FIRST_NAME                          VARCHAR (50) NOT NULL,
    LAST_NAME                           VARCHAR (50) NOT NULL,
    EMAIL_ADDRESS                       VARCHAR (320) NOT NULL,
    TELEPHONE_NUMBER                    VARCHAR (15) NOT NULL,
    INSERT_TIME                         TIME DEFAULT NOW() NOT NULL,
    UPDATE_TIME                         TIME,
    CONSTRAINT REFERENT_PK PRIMARY KEY (REFERENT_K)
);
CREATE SEQUENCE REFERENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE PROFILE (
    PROFILE_K                           BIGINT NOT NULL,
    FULL_NAME                           VARCHAR(100) NOT NULL,
    NAME                                VARCHAR(100),
    PEC_ADDRESS                         VARCHAR (320) NOT NULL,
    DESCRIPTION                         VARCHAR (300) NOT NULL,
    SALES_CHANNEL                       VARCHAR (50) NOT NULL,
    WEBSITE_URL                         VARCHAR (500),
    INSERT_TIME                         TIME DEFAULT NOW() NOT NULL,
    UPDATE_TIME                         TIME,
    AGREEMENT_FK                        VARCHAR(36) NOT NULL,
    REFERENT_FK                         BIGINT NOT NULL,
    CONSTRAINT PROFILE_PK PRIMARY KEY (PROFILE_K),
    CONSTRAINT PROFILE_AGREEMENT_FK FOREIGN KEY (AGREEMENT_FK) REFERENCES AGREEMENT(AGREEMENT_K),
    CONSTRAINT PROFILE_REFERENT_FK FOREIGN KEY (REFERENT_FK) REFERENCES REFERENT(REFERENT_K)
);
CREATE SEQUENCE PROFILE_SEQ START WITH 1 INCREMENT BY 1;
CREATE UNIQUE INDEX IDX_PROFILE_AGREEMENT ON PROFILE(AGREEMENT_FK);
CREATE UNIQUE INDEX IDX_PROFILE_REFERENT_FK ON PROFILE(REFERENT_FK);

CREATE TABLE ADDRESS (
    ADDRESS_K                           BIGINT NOT NULL,
    STREET                              VARCHAR(255) NOT NULL,
    ZIP_CODE                            VARCHAR(5) NOT NULL,
    CITY                                VARCHAR(255) NOT NULL,
    DISTRICT                            VARCHAR(2) NOT NULL,
    LATITUDE                            DOUBLE PRECISION,
    LONGITUDE                           DOUBLE PRECISION,
    PROFILE_FK                          BIGINT NOT NULL,
    INSERT_TIME                         TIME DEFAULT NOW() NOT NULL,
    UPDATE_TIME                         TIME,
    CONSTRAINT ADDRESS_PK PRIMARY KEY (ADDRESS_K),
    CONSTRAINT ADDRESS_PROFILE_FK FOREIGN KEY (PROFILE_FK) REFERENCES PROFILE(PROFILE_K)
 );
CREATE SEQUENCE ADDRESS_SEQ START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_ADDRESS_PROFILE_FK ON ADDRESS(PROFILE_FK);


CREATE TABLE DISCOUNT (
    DISCOUNT_K                          BIGINT NOT NULL,
    STATE                               VARCHAR (50) NOT NULL,
    NAME                                VARCHAR (100) NOT NULL,
    DESCRIPTION                         VARCHAR (250) NOT NULL,
    START_DATE                          DATE NOT NULL,
    END_DATE                            DATE NOT NULL,
    DISCOUNT_VALUE                      DOUBLE PRECISION NOT NULL,
    CONDITION                           VARCHAR (200) NOT NULL,        
    STATIC_CODE                         VARCHAR (100),
    AGREEMENT_FK                        VARCHAR(36) NOT NULL,
    INSERT_TIME                         TIME DEFAULT NOW() NOT NULL,
    UPDATE_TIME                         TIME,
    CONSTRAINT DISCOUNT_PK PRIMARY KEY (DISCOUNT_K),
    CONSTRAINT DISCOUNT_AGREEMENT_FK FOREIGN KEY (AGREEMENT_FK) REFERENCES AGREEMENT(AGREEMENT_K)
);
CREATE SEQUENCE DISCOUNT_SEQ START WITH 1 INCREMENT BY 1;
CREATE INDEX IDX_DISCOUNT_AGREEMENT ON DISCOUNT(AGREEMENT_FK);


CREATE TABLE DISCOUNT_PRODUCT_CATEGORY (
    PRODUCT_CATEGORY                    VARCHAR (100) NOT NULL,
    DISCOUNT_FK                         BIGINT NOT NULL,
    INSERT_TIME                         TIME DEFAULT NOW() NOT NULL,
    UPDATE_TIME                         TIME,
    CONSTRAINT DISCOUNT_PRODUCT_CATEGORY_PK PRIMARY KEY (DISCOUNT_FK, PRODUCT_CATEGORY),
    CONSTRAINT DISCOUNT_PRODUCT_CATEGORY_FK FOREIGN KEY (DISCOUNT_FK) REFERENCES DISCOUNT(DISCOUNT_K)
);

   